version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=tadb_user
      - DB_PASSWORD=tadb_password
      - DB_NAME=tadb
      - PORT=8080
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tadb_user
      - POSTGRES_PASSWORD=tadb_password
      - POSTGRES_DB=tadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
