name: Check & deploy API documentation
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: Generate Swagger (swag)
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          export PATH="$HOME/go/bin:$PATH"
          swag init -g cmd/main.go -o docs
      - name: Convert to OpenAPI 3
        run: |
          go run ./cmd/convert-openapi --in docs/swagger.yaml --out docs/openapi.yaml
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: tadb
          token: ${{ secrets.BUMP_SH_TOKEN }}
          file: docs/openapi.yaml
  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: Generate Swagger (swag)
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          export PATH="$HOME/go/bin:$PATH"
          swag init -g cmd/main.go -o docs
      - name: Convert to OpenAPI 3
        run: |
          go run ./cmd/convert-openapi --in docs/swagger.yaml --out docs/openapi.yaml
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: tadb
          token: ${{ secrets.BUMP_SH_TOKEN }}
          file: docs/openapi.yaml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
